name: Reporter
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:12
    steps:
      - name: Checkout reposistório
        uses: actions/checkout@v2
      - name: Instalar dependências do projeto
        run: npm ci
      - name: Instalar CC Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - id: test-runner
        name: Executar testes
        run: npm test
      - id: test-reporter-success
        name: Enviar relatório dos testes com sucesso
        if: ${{ success() }}
        run: | 
          ls -la
          ./cc-test-reporter format-coverage -d -t lcov -o ${{github.workspace}}/coverage/codeclimate.json ${{github.workspace}}/coverage/lcov.info
          ./cc-test-reporter upload-coverage
      - id: test-reporter-failure
        name: Enviar relatório dos testes com falha
        if: ${{ failure() }}
        run: | 
          ls -la
          ./cc-test-reporter format-coverage -d -t lcov -o ${{github.workspace}}/coverage/codeclimate.json ${{github.workspace}}/coverage/lcov.info
          ./cc-test-reporter upload-coverage
  