name: Reporter
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:12
    steps:
      - name: Checkout reposistório
        uses: actions/checkout@v2
        with:
          clean: false
          fetch-depth: 0
      - name: Instalar dependências do projeto
        run: npm ci
      - name: Instalar Test Reporter
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
      - id: test-runner
        name: Executar testes
        run: | 
          ./cc-test-reporter before-build
          npm test
      - id: test-reporter-success
        name: Enviar Test Reporter - Sucesso
        if: ${{ success() }}
        env:
          CI_BUILD_ID: ${{github.run_id}}
          CI_NAME: github
          GIT_BRANCH: master
          GIT_COMMIT_SHA: ${{github.sha}}
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          export GIT_COMMITTED_AT="$(date +%s)"
          ./cc-test-reporter after-build --debug -t lcov -p ${{github.workspace}} --exit-code 0
      - id: test-reporter-fails
        name: Enviar Test Reporter - Falha
        if: ${{ failure() }}
        env:
          CI_BUILD_ID: ${{github.run_id}}
          CI_NAME: github
          GIT_BRANCH: master
          GIT_COMMIT_SHA: ${{github.sha}}
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          export GIT_COMMITTED_AT="$(date +%s)"
          ./cc-test-reporter after-build --debug -t lcov -p ${{github.workspace}} --exit-code 1
          
  